name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Log in to Docker
        run: |
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u protomybot --password-stdin
          echo $QUAY_TOKEN | docker login quay.io -u $QUAY_USERNAME --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
